// NOTE: This file is generated by scripts/generate-theme-css.js — do not edit by hand.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark']
    }
}

export {}
