// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "'nQYQPOOOOQO'#Ct'#CtObQQO'#C`OpQQO'#C_OxQPO'#C_OOQO'#Cr'#CrOOQO'#DO'#DOOOQO'#Cs'#CsQYQPOOOOQO-E6r-E6rO!`QPO'#CuO!gQQO,58yOOQO,58y,58yO!oQPO,58yOOQO-E6q-E6qOOQO'#Cv'#CvO!tQSO'#CfO#RQSO'#CeOOQO'#Cm'#CmO#^QPO'#ClOOQO'#Cd'#CdOOQO,59a,59aOOQO-E6s-E6sOOQO1G.e1G.eO#cQQO'#CbO#nQQO1G.eOOQO-E6t-E6tO}QPO'#CwO#vQSO,59PO$RQWO,59WO$WQQO7+$POOQO7+$P7+$POOQO,59c,59cOOQO-E6u-E6uOOQO'#Cx'#CxO$`QWO'#CoO$nQQO'#CnOOQO1G.r1G.rOOQO<<Gk<<GkOOQO-E6v-E6vO$yQWO'#CyO%OQQO,59YOOQO'#Cq'#CqO%ZQSO,59eOOQO-E6w-E6wO$yQWO'#CzO%cQSO1G/POOQO1G/P1G/POOQO,59f,59fOOQO-E6x-E6xOOQO7+$k7+$k",
  stateData:
    "%u~OqOSPOS~OTPOxTO~OTPOVUXsSXwUX~OVYOw[O~Os]O~OZ_O[_O]_O^_O__O~OTbO~P}OVYOwgO~OTPO~OVYXtYXwYX~P}OtkOVXXwXX~OsmO~OTPOVUXwUX~OVYOwoO~OtkOVXawXa~OdrO~OVYOwvO~OdrOVcXucXwcX~OuxOVbXwbX~OdzO~OuxOVbawba~Ot}Ov!PO~Ot}Ov!SO~OZ[PV^_]_T~",
  goto:
    "$QsPPPtxP|P!T!W!ZPPPPP!W!a!d!gP!jt!p!v#R#]#d#j#p#vPPP#|TUOWTSOWSROWRi]ReYRdYQaYRpkRcYRumRtmQ{xR!Q}QWOR^WSQOWSXQhRh]QZRSfZnRniS`YkRj`QlaRqlQsmRwsQytR|yQ!O{R!R!OTVOW",
  nodeNames:
    "⚠ LineComment Program ExerciseExpression ExerciseLabel Word ExerciseName SectionSeparator ExerciseSection ExerciseSets ExerciseSet Rpe Timer SetPart Weight Percentage ExerciseProperty ExercisePropertyName FunctionExpression FunctionName Alphanumeric FunctionArgument EmptyExpression",
  maxTerm: 40,
  skippedNodes: [0, 1],
  repeatNodeCount: 8,
  tokenData:
    ",Q~RbXY!ZYZ!f]^!mpq!Zxy!wyz!||}#R}!O$T!P!Q$|!Q![&e![!]+k!b!c+p!c!}'r#R#S'r#T#l'r#l#m*u#m#o'r~~+{~!`Qq~XY!Zpq!Z_!mOxPw^_!tPxPw^YZ!f~!|Ou~~#ROv~V#YUtSTR|}#l}!O#l!Q![#l!c!}#l#R#S#l#T#o#lR#qUTR|}#l}!O#l!Q![#l!c!}#l#R#S#l#T#o#lV$[X]TTR{|$w|}#l}!O$T!Q![$T!c!}#l#R#S#l#T#l#l#l#m$T#m#o#lT$|O]T~%RPV~!P!Q%U~%XVOY%UYZ%nZ]%U]^%s^;'S%U;'S;=`&_<%lO%U~%sOP~~%xVP~OY%UYZ%nZ]%U]^%s^;'S%U;'S;=`&_<%lO%U~&bP;=`<%l%U_&n_dW]TTRuv'm{|$w|}#l}!O$T!Q![&e!c!}'r#R#S'r#T#_'r#_#`(]#`#a)i#a#g'r#g#h*Y#h#l'r#l#m*u#m#o'rT'rO_TZ'yUdWTR|}#l}!O#l!Q!['r!c!}'r#R#S'r#T#o'r_(dWdWTR|}#l}!O#l!Q!['r!c!}'r#R#S'r#T#Z'r#Z#[(|#[#o'r_)VUdW^TTR|}#l}!O#l!Q!['r!c!}'r#R#S'r#T#o'r_)pWdWTR|}#l}!O#l!Q!['r!c!}'r#R#S'r#T#U'r#U#V(|#V#o'r_*cUdW[TTR|}#l}!O#l!Q!['r!c!}'r#R#S'r#T#o'r_+OXdW]TTR{|$w|}#l}!O$T!Q![*u!c!}'r#R#S'r#T#l'r#l#m*u#m#o'r~+pOs~~+sP!Q![+v~+{OZ~^,QOw^",
  tokenizers: [0, 1, 2, 3],
  topRules: { Program: [0, 2] },
  tokenPrec: 211,
});
