/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable no-template-curly-in-string */
import { LRParser } from "@lezer/lr";
const spec_Keyword = { __proto__: null, none: 120 } as any;
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "+WQVQPOOOOQO'#DR'#DROkQQO'#CcOvQQO'#CbOOQO'#DP'#DPOOQO'#D]'#D]OOQO'#DQ'#DQQVQPOOOOQO-E7P-E7PO!OQSO'#DSO!gQQO,58|OOQO,58|,58|OOQO-E7O-E7OOOQO'#Cg'#CgOOQO'#Ci'#CiO#^QWO'#CnOOQO'#Cq'#CqO#nQWO'#CpO#yQSO'#CtO$jQSO'#DOO$qQSO'#ChO$RQSO'#DOO$vQWO'#DOOOQO'#DW'#DWO${QSO'#C|O%aQSO'#C{OOQO'#Cf'#CfOOQO,59n,59nOOQO-E7Q-E7QOOQO1G.h1G.hOOQO,59i,59iOOQO,59[,59[OOQO,59_,59_O%lQSO,59`O&WQSO,59aOOQO,59j,59jO&]QSO,59SO&WQSO,59jOOQO-E7U-E7UO&kQSO'#DXO&vQSO,59gOOQO1G.z1G.zOOQO'#Cn'#CnOOQO1G.{1G.{OOQO'#Cl'#ClO!oQWO'#CnO'RQSO'#CkOOQO'#Cx'#CxO'^QWO'#CxOOQO'#DU'#DUO'cQSO'#CwOOQO'#Cz'#CzO'tQSO'#CvOOQO'#Cv'#CvOOQO1G.n1G.nO(hQSO1G/UO(PQSO1G/UOOQO,59s,59sOOQO-E7V-E7VO(oQSO,59VO&WQSO,59dOOQO-E7S-E7SO(zQSO'#DVO)SQSO,59bOOQO7+$p7+$pO)_QWO'#CnO)sQSO'#CmOOQO'#Cm'#CmO*OQSO1G.qOOQO1G/O1G/OOOQO,59q,59qOOQO-E7T-E7TO(oQSO'#DTO*WQSO7+$]OOQO7+$]7+$]OOQO,59o,59oOOQO-E7R-E7ROOQO<<Gw<<Gw",
  stateData:
    "*g~O!OOS~OQTORTOSTOTTOWPO!aSO~OWPOXVX!`VX~OXXO!`ZO~O^^Oc_Of`O!Q]O!WbOXvX!`vX~OXXO!`mO~OXbXcbXfbX!TeX!UeX!VeX!ZbX!]mX!`bX~O!_nO!WbX!XbX!YbX~P!oO!ToO!UoO!VpO~Oc`Of`O~O!XsOXrXcrXfrX!WrX!ZrX!`rX~O!YrO~P$RO!RtO~O!]uO~Oc_Of`O!WbOXpX!ZpX!`pX~O!ZwOXoX!`oX~O!XyOXhachafha!Wha!Zha!`ha![ha~OczO~O^|Oc}Of`O!^!TO~Oc_Of`O!WbO~O!ZwOXoa!`oa~O!S!]OX_X!`_X~O!]!^O~Oc}Of`OXkX!ZkX!`kX~O!Z!`OXjX!`jX~O!X!bOXricrifri!Wri!Zri!`ri~O!YrO~P(POc!cOf`O!WbO~Oc}Of`O~O!Z!`OXja!`ja~O!TeX!UeX!VeX!YbX!ZbX![bX~O!YrO!ZaX![aX~O!Z!jO![!lO~O!Z!jO![!oO~OfcRQTS~",
  goto:
    "&X!QPPPPPP!R!VPP!Z!^!^!aP!d!g!j!pP#X#gP#X#t#}!d$Z$a$f$p!^$s$y$y!R%O%U%]%c%i%p%v%}PPP&TTTOVTROVRkXRjXRdXR!WtR!OtQ!f!]R!m!jUcXhwQ{rU!Pt!S!`Q!XuS!d!]!jR!g!^UgXhwU!Rt!S!`T!e!]!j`aXhtw!S!]!`!jRqbUgXhwT!e!]!jUeXhwQ!YuT!e!]!jQ!UtR!h!`V!Rt!S!`UfXhwV!Qt!S!`R!VtQiXR!ZwVgXhwQVOR[VSQOVRWQQYRRlYQ!k!fR!n!kS!St!`R!_!SQ!a!UR!i!aShXwRvhQxiR![xTUOV",
  nodeNames:
    "⚠ Program LineComment TripleLineComment Week Day ExerciseExpression ExerciseName NonSeparator SectionSeparator ExerciseSection ReuseSection ExerciseProperty ExercisePropertyName Keyword FunctionExpression FunctionName FunctionArgument Rep Int Weight Number Float Percentage Rpe RepRange WarmupExerciseSets WarmupExerciseSet WarmupSetPart Set None ExerciseSets ExerciseSet Timer SetPart EmptyExpression",
  maxTerm: 63,
  skippedNodes: [0],
  repeatNodeCount: 8,
  tokenData:
    "?k~RyOX#rXY$gYZ$rZ]#r]^$y^p#rpq$gqs#rst%Ttu#ruv)Vvx#rxy)vyz*gz{#r{|+W|}+w}!O,h!O!P-X!P!Q0R!Q![4]![!]5t!]!b#r!b!c6e!c!}7U!}#R#r#R#S7U#S#T#r#T#_7U#_#`8[#`#a:p#a#g7U#g#h=U#h#l7U#l#m>^#m#o7U#o;'S#r;'S;=`$a<%l~#r~O#r~~?fR#wWWROX#rZ]#r^p#rqs#rt!P#r!Q;'S#r;'S;=`$a<%lO#rR$dP;=`<%l#r~$lQ!O~XY$gpq$g_$yO!aP!`^_%QP!aP!`^YZ$r~%WZOY%yYZ&iZ]%y]^&n^s%yst'ft;'S%y;'S;=`'`<%l~%y~O%y~~&i~%|XOY%yYZ&iZ]%y]^&n^;'S%y;'S;=`'`<%l~%y~O%y~~&i~&nOS~~&sXS~OY%yYZ&iZ]%y]^&n^;'S%y;'S;=`'`<%l~%y~O%y~~&i~'cP;=`<%l%y~'iXOY'fYZ(UZ]'f]^(]^;'S'f;'S;=`)P<%l~'f~O'f~~(U~(]OT~S~~(dXT~S~OY'fYZ(UZ]'f]^(]^;'S'f;'S;=`)P<%l~'f~O'f~~(U~)SP;=`<%l'fZ)^W!VWWROX#rZ]#r^p#rqs#rt!P#r!Q;'S#r;'S;=`$a<%lO#rV)}W!SSWROX#rZ]#r^p#rqs#rt!P#r!Q;'S#r;'S;=`$a<%lO#r_*nW![[WROX#rZ]#r^p#rqs#rt!P#r!Q;'S#r;'S;=`$a<%lO#r_+_W!X[WROX#rZ]#r^p#rqs#rt!P#r!Q;'S#r;'S;=`$a<%lO#r_,OW!Z[WROX#rZ]#r^p#rqs#rt!P#r!Q;'S#r;'S;=`$a<%lO#r_,oW!Y[WROX#rZ]#r^p#rqs#rt!P#r!Q;'S#r;'S;=`$a<%lO#r_-^YWROX#rZ]#r^p#rqs#rt!O#r!O!P-|!Q![/_![;'S#r;'S;=`$a<%lO#rV.RXWROX#rZ]#r^p#rqs#rt!O#r!O!P.n!Q;'S#r;'S;=`$a<%lO#rV.uW!QSWROX#rZ]#r^p#rqs#rt!P#r!Q;'S#r;'S;=`$a<%lO#r_/fXWRf[OX#rZ]#r^p#rqs#rt!P#r!Q![/_![;'S#r;'S;=`$a<%lO#r_0WPX^!P!Q0ZP0^ZOY1PYZ1oZ]1P]^1t^!P1P!P!Q2l!Q;'S1P;'S;=`2f<%l~1P~O1P~~1oP1SXOY1PYZ1oZ]1P]^1t^;'S1P;'S;=`2f<%l~1P~O1P~~1oP1tOQPP1yXQPOY1PYZ1oZ]1P]^1t^;'S1P;'S;=`2f<%l~1P~O1P~~1oP2iP;=`<%l1PP2oXOY2lYZ3[Z]2l]^3c^;'S2l;'S;=`4V<%l~2l~O2l~~3[P3cORPQPP3jXRPQPOY2lYZ3[Z]2l]^3c^;'S2l;'S;=`4V<%l~2l~O2l~~3[P4YP;=`<%l2l_4dYWRc[OX#rZ]#r^p#rqs#rt!O#r!O!P5S!Q![4]![;'S#r;'S;=`$a<%lO#r_5XXWROX#rZ]#r^p#rqs#rt!P#r!Q![/_![;'S#r;'S;=`$a<%lO#rV5{W!RSWROX#rZ]#r^p#rqs#rt!P#r!Q;'S#r;'S;=`$a<%lO#r_6lW!W[WROX#rZ]#r^p#rqs#rt!P#r!Q;'S#r;'S;=`$a<%lO#rV7]_^SWROX#rZ]#r^p#rqs#rt!P#r!Q![7U![!c#r!c!}7U!}#R#r#R#S7U#S#T#r#T#o7U#o;'S#r;'S;=`$a<%lO#r_8ca^SWROX#rZ]#r^p#rqs#rt!P#r!Q![7U![!c#r!c!}7U!}#R#r#R#S7U#S#T#r#T#Z7U#Z#[9h#[#o7U#o;'S#r;'S;=`$a<%lO#r_9q_!TW^SWROX#rZ]#r^p#rqs#rt!P#r!Q![7U![!c#r!c!}7U!}#R#r#R#S7U#S#T#r#T#o7U#o;'S#r;'S;=`$a<%lO#r_:wa^SWROX#rZ]#r^p#rqs#rt!P#r!Q![7U![!c#r!c!}7U!}#R#r#R#S7U#S#T#r#T#U7U#U#V;|#V#o7U#o;'S#r;'S;=`$a<%lO#r_<V_!UW^SWROX#rZ]#r^p#rqs#rt!P#r!Q![7U![!c#r!c!}7U!}#R#r#R#S7U#S#T#r#T#o7U#o;'S#r;'S;=`$a<%lO#r_=__!_W^SWROX#rZ]#r^p#rqs#rt!P#r!Q![7U![!c#r!c!}7U!}#R#r#R#S7U#S#T#r#T#o7U#o;'S#r;'S;=`$a<%lO#r_>g_!]W^SWROX#rZ]#r^p#rqs#rt!P#r!Q![7U![!c#r!c!}7U!}#R#r#R#S7U#S#T#r#T#o7U#o;'S#r;'S;=`$a<%lO#r^?kO!`^",
  tokenizers: [0, 1, 2, 3],
  topRules: { Program: [0, 1] },
  specialized: [{ term: 14, get: (value: any) => spec_Keyword[value] || -1 }],
  tokenPrec: 430,
});
