/* eslint-disable no-template-curly-in-string */
/* eslint-disable @typescript-eslint/no-explicit-any */
import { LRParser } from "@lezer/lr";
const spec_Keyword: any = { __proto__: null, none: 132 };
export const parser = LRParser.deserialize({
  version: 14,
  states:
    ".^QVQPOOOOQO'#DW'#DWOkQQO'#CcOvQQO'#CbOOQO'#DU'#DUOOQO'#Db'#DbOOQO'#DV'#DVQVQPOOOOQO-E7U-E7UO!OQSO'#DXO!jQQO,58|OOQO,58|,58|OOQO-E7T-E7TOOQO'#Ch'#ChO!rQWO'#CmOOQO'#Cp'#CpO#WQWO'#CoO#cQSO'#CsO#nQSO'#CgOOQO'#DP'#DPO#sQWO'#DSO#{QPO'#DTOOQO'#D]'#D]O$QQSO'#DQO$iQSO'#DOO$tQSO'#DOOOQO'#Cf'#CfOOQO,59s,59sOOQO-E7V-E7VOOQO1G.h1G.hOOQO,59m,59mOOQO,59Z,59ZOOQO,59^,59^O%SQSO,59_OOQO,59_,59_O%qQSO,59RO&PQSO,59nO&UQWO,59nO&ZQPO,59oOOQO-E7Z-E7ZO$tQSO'#D^O&cQSO,59jO&cQSO,59jOOQO1G.y1G.yOOQO'#Ck'#CkO&nQWO'#CmO'cQQO'#CjO'tQWO'#C|OOQO'#DZ'#DZO(YQSO'#C{OOQO'#C}'#C}O(kQSO'#CzOOQO'#Cz'#CzOOQO1G.m1G.mOOQO'#Cm'#CmO)bQSO1G/YO(vQSO1G/YO&PQSO1G/YOOQO1G/Z1G/ZOOQO,59x,59xOOQO-E7[-E7[O)iQSO1G/UO)tQSO'#CxOOQO,59U,59UO)yQSO,59UO&PQSO,59hOOQO-E7X-E7XO*_QSO'#D[O*gQSO,59fO&PQSO,59aOOQO7+$t7+$tO+^QSO7+$tO*rQSO7+$tO+eQPO'#CyO+mQPO,59dO+rQSO'#ClO+}QSO'#CvOOQO'#Cl'#ClO,SQSO'#DYO,bQSO1G.pO,jQQO1G.pO,bQSO1G.pOOQO1G/S1G/SOOQO,59v,59vOOQO-E7Y-E7YOOQO1G.{1G.{OOQO<<H`<<H`O,xQPO'#CcOOQO,59e,59eOOQO1G/O1G/OO-QQSO,59bOOQO,59t,59tOOQO-E7W-E7WO-YQQO7+$[OOQO7+$[7+$[O-hQSO7+$[O-pQWO1G.|O.UQSO1G.|OOQO<<Gv<<GvO.aQQO<<GvOOQO7+$h7+$hOOQOAN=bAN=b",
  stateData:
    ".v~O!TOS~OQTORTOSTOTTOWPO!hSO~OWPOXVX!gVX~OXXO!gZO~O]]Ob^Oe_O!WeO![aO!ecOX{X!g{X~OXXO!gmO~O!fnOhaX!XdX!YdX!ZdX!caX~O!XoO!YoO!ZpO~Ob_Oe_OhrO~O!VsO~OhuO!ctO~OWPO~Ob^Oe_O!WeO![aOXtX!^tX!gtX~O!^xOXrX!grX~Ob^Oe_O!WeO![aO~Oh{OXgabgaega!Wga![ga!^ga!gga!_ga~O]|Ob}Oe_O!d!SO~Ob!WO~O!c!ZO~OWPO!_![O~O!^xOXra!gra~OXaXbaXeaX!XdX!YdX!ZdX!^aX!caX!gaX!]aX!_aX~Ok!aO!W!bO!`!`OX^X!g^X~O!c!cOXpXbpXepX!^pX!gpX~Ob}Oe_OXoX!^oX!goX~O!^!eOXnX!gnX~Oh!hOXvibvievi!Wvi![vi!^vi!gvi~O!]!gO~P(vO!^xOXri!gri~O!a!kO~O]!nOb}Oe_O![aO!^!pO!_!rO~Ob}Oe_O~O!^!eOXna!gna~Oh!xOXvqbvqevq!Wvq![vq!^vq!gvq~O!]!gO~P*rOWPO!bmX~O!b!{O~O!]!gO!^`X!_`X~O!V!|O~O]!nOb}Oe_O![aO~O!^!pO!_#PO~Ok#QO!`!`OX^i!g^i~OWPO!bVX~Ob#SOe#SO~Ok#UO!`!`OX^q!g^q~O!^!pO!_#VO~Oh#WO!XdX!YdX!ZdX!^ji!_ji~Oh#WO!^ji!_ji~Ok#XO!`!`OX^y!g^y~OebRQTS~",
  goto:
    "'X!VPPPPPP!W![PP!c!f!iP!l!o!r!xP#e#wP#e$WP$b$^P$l$x!l${%R%W!f%Z%^%g%g%g!W%m%s&S&Y&d&k&q&yPPP'TTTOVSROVR!z!kRkXRjXRbXR!VsR!OsQ!s!bR!}!pWdXgixU!Ps!R!eQ!XtQ!i!ZS!m!b!pQ!t!cR!w!gWfXgixU!Qs!R!eS!o!b!pR#T!|d`Xgisx!R!b!e!p!|RqaWfXgixT!o!b!pQ!YtQ!j!ZT!o!b!pQ!a!OQ#Q!rQ#U#PR#X#VR!l!`Q!TsR!u!eV!Qs!R!eR!UsRiXQhXQziR!]xXfXgixQVOR[VSQOVUWQv!yQveR!y!kQYRRlYQ!q!bS#O!q#RR#R!sS!Rs!eR!d!RQ!f!TR!v!fUgXixRwgQyhS!^y!_R!_zTUOV",
  nodeNames:
    "⚠ Program LineComment TripleLineComment Week Day ExerciseExpression ExerciseName NonSeparator SectionSeparator ExerciseSection ExerciseProperty ExercisePropertyName Keyword FunctionExpression FunctionName FunctionArgument Rep Int Weight Number Float Percentage Rpe Plus RepRange KeyValue Liftoscript ReuseLiftoscript ReuseSection WarmupExerciseSets WarmupExerciseSet WarmupSetPart None ExerciseSets CurrentVariation ExerciseSet Timer SetPart SetLabel EmptyExpression",
  maxTerm: 70,
  skippedNodes: [0],
  repeatNodeCount: 8,
  tokenData:
    "DS~R}OX$OXY$|YZ%XZ]$O]^%`^p$Opq$|qr%jrs$Ost&dtu$Ouv*fvx$Oxy+`yz+ez{$O{|+j|},d}!O-^!O!P.W!P!Q1v!Q![6Q![!]7{!]!b$O!b!c8u!c!}9o!}#R$O#R#S9o#S#T$O#T#_9o#_#`:{#`#a=m#a#g9o#g#h@_#h#l9o#l#mAm#m#o9o#o#pB{#p#q$O#q#rCx#r;'S$O;'S;=`$v<%l~$O~O$O~~C}R$TZWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$OR$yP;=`<%l$O~%RQ!T~XY$|pq$|_%`O!hP!g^_%gP!hP!g^YZ%XV%qZ!eSWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$O~&gZOY'YYZ'xZ]'Y]^'}^s'Yst(ut;'S'Y;'S;=`(o<%l~'Y~O'Y~~'x~']XOY'YYZ'xZ]'Y]^'}^;'S'Y;'S;=`(o<%l~'Y~O'Y~~'x~'}OS~~(SXS~OY'YYZ'xZ]'Y]^'}^;'S'Y;'S;=`(o<%l~'Y~O'Y~~'x~(rP;=`<%l'Y~(xXOY(uYZ)eZ](u]^)l^;'S(u;'S;=`*`<%l~(u~O(u~~)e~)lOT~S~~)sXT~S~OY(uYZ)eZ](u]^)l^;'S(u;'S;=`*`<%l~(u~O(u~~)e~*cP;=`<%l(uZ*mZ!ZWWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$O~+eO!W~~+jO!_~_+qZWRh[OX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$O_,kZ!^[WROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$O_-eZ!][WROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$O_.]]WROX$OZ]$O^p$Oqs$Otx$Oz!O$O!O!P/U!Q![0y![#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$OV/Z[WROX$OZ]$O^p$Oqs$Otx$Oz!O$O!O!P0P!Q#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$OV0WZ!aSWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$O_1Q[WRe[OX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q![0y![#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$O_1{PX^!P!Q2OP2RZOY2tYZ3dZ]2t]^3i^!P2t!P!Q4a!Q;'S2t;'S;=`4Z<%l~2t~O2t~~3dP2wXOY2tYZ3dZ]2t]^3i^;'S2t;'S;=`4Z<%l~2t~O2t~~3dP3iOQPP3nXQPOY2tYZ3dZ]2t]^3i^;'S2t;'S;=`4Z<%l~2t~O2t~~3dP4^P;=`<%l2tP4dXOY4aYZ5PZ]4a]^5W^;'S4a;'S;=`5z<%l~4a~O4a~~5PP5WORPQPP5_XRPQPOY4aYZ5PZ]4a]^5W^;'S4a;'S;=`5z<%l~4a~O4a~~5PP5}P;=`<%l4a_6X]WRb[OX$OZ]$O^p$Oqs$Otx$Oz!O$O!O!P7Q!Q![6Q![#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$O_7V[WROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q![0y![#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$OV8SZ!VSWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$OV8|Z![SWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q#o$O#p#q$O#r;'S$O;'S;=`$v<%lO$OV9va]SWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q![9o![!c$O!c!}9o!}#R$O#R#S9o#S#T$O#T#o9o#p#q$O#r;'S$O;'S;=`$v<%lO$O_;Sc]SWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q![9o![!c$O!c!}9o!}#R$O#R#S9o#S#T$O#T#Z9o#Z#[<_#[#o9o#p#q$O#r;'S$O;'S;=`$v<%lO$O_<ha!XW]SWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q![9o![!c$O!c!}9o!}#R$O#R#S9o#S#T$O#T#o9o#p#q$O#r;'S$O;'S;=`$v<%lO$O_=tc]SWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q![9o![!c$O!c!}9o!}#R$O#R#S9o#S#T$O#T#U9o#U#V?P#V#o9o#p#q$O#r;'S$O;'S;=`$v<%lO$O_?Ya!YW]SWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q![9o![!c$O!c!}9o!}#R$O#R#S9o#S#T$O#T#o9o#p#q$O#r;'S$O;'S;=`$v<%lO$O_@ha!fW]SWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q![9o![!c$O!c!}9o!}#R$O#R#S9o#S#T$O#T#o9o#p#q$O#r;'S$O;'S;=`$v<%lO$O_Ava!cW]SWROX$OZ]$O^p$Oqs$Otx$Oz!P$O!Q![9o![!c$O!c!}9o!}#R$O#R#S9o#S#T$O#T#o9o#p#q$O#r;'S$O;'S;=`$v<%lO$O~CQP!`~#r#sCT~CWTO#rCT#r#sCg#s;'SCT;'S;=`Cr<%lOCT~CjP#q#rCm~CrOk~~CuP;=`<%lCT~C}O!b~^DSO!g^",
  tokenizers: [0, 1, 2, 3],
  topRules: { Program: [0, 1] },
  specialized: [{ term: 13, get: (value: any) => spec_Keyword[value] || -1 }],
  tokenPrec: 629,
});
