// Generated by scripts/generate-theme-css.js — do not edit by hand.
export const SCALED_SPACINGS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 20, 24, 28, 32, 36, 40, 44, 48, 56, 60, 64, 72, 80, 96];
export const SCALED_LEADINGS = [3, 4, 5, 6, 7, 8, 9, 10, 12];
