const fs = require("fs");
const path = require("path");

function parseSpriteByGroups(svgContent, idRegex) {
  const result = {};
  const lines = svgContent.split("\n");
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const match = line.match(idRegex);
    if (match) {
      const id = match[1];
      const collected = [line];
      let depth = 1;
      i++;
      while (i < lines.length && depth > 0) {
        const inner = lines[i];
        const openCount = (inner.match(/<g[\s>]/g) || []).length;
        const closeCount = (inner.match(/<\/g>/g) || []).length;
        depth += openCount;
        depth -= closeCount;
        collected.push(inner);
        i++;
      }
      result[id] = collected.join("\n");
    } else {
      i++;
    }
  }
  return result;
}

function processSvgFile(inputPath, outputPath, varName, idRegex) {
  const content = fs.readFileSync(inputPath, "utf8");
  const groups = parseSpriteByGroups(content, idRegex);
  console.log(
    `Extracted ${Object.keys(groups).length} groups from ${path.basename(inputPath)}: ${Object.keys(groups).join(", ")}`
  );

  const lines = [
    "// AUTO-GENERATED by scripts/extractMuscleSprites.js — do not edit by hand",
    "",
    `export const ${varName}: Record<string, string> = {`,
  ];
  for (const [id, body] of Object.entries(groups)) {
    const wrapped = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 61 48">${body}</svg>`;
    const escaped = wrapped.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
    const key = /^[a-z_][a-z0-9_]*$/i.test(id) ? id : JSON.stringify(id);
    lines.push(`  ${key}: \`${escaped}\`,`);
  }
  lines.push("};");
  lines.push("");

  fs.writeFileSync(outputPath, lines.join("\n"));
  console.log(`Wrote ${outputPath}`);
}

const repoRoot = path.resolve(__dirname, "..");
processSvgFile(
  path.join(repoRoot, "images/svgs/musclegroups-combined.svg"),
  path.join(repoRoot, "src/components/muscleGroupSpriteData.ts"),
  "MUSCLE_GROUP_SPRITES",
  /<g id="(\w+)" viewBox="0 0 61 4[78]">/
);
processSvgFile(
  path.join(repoRoot, "images/svgs/muscles-combined.svg"),
  path.join(repoRoot, "src/components/muscleSpriteData.ts"),
  "MUSCLE_SPRITES",
  /<g id="([a-z0-9]+)" viewBox="0 0 61 4[78]">/
);
