import { IWeight, Weight, IBars, TBarKey, IBarKey } from "./weight";
import { ISet } from "./set";
import * as t from "io-ts";
import { IArrayElement } from "../utils/types";
import { ISettings, Settings } from "./settings";
import { ObjectUtils } from "../utils/object";

export const exerciseTypes = [
  "abWheel",
  "arnoldPress",
  "backExtension",
  "ballSlams",
  "battleRopes",
  "benchDip",
  "benchPress",
  "benchPressCloseGrip",
  "benchPressWideGrip",
  "bentOverOneArmRow",
  "bentOverRow",
  "bicepCurl",
  "bicycleCrunch",
  "boxJump",
  "boxSquat",
  "bulgarianSplitSquat",
  "burpee",
  "cableCrossover",
  "cableCrunch",
  "cableKickback",
  "cablePullThrough",
  "cableTwist",
  "calfPressOnLegPress",
  "calfPressOnSeatedLegPress",
  "chestDip",
  "chestFly",
  "chestPress",
  "chinUp",
  "clean",
  "cleanandJerk",
  "concentrationCurl",
  "crossBodyCrunch",
  "crunch",
  "cycling",
  "deadlift",
  "deadliftHighPull",
  "declineBenchPress",
  "declineCrunch",
  "deficitDeadlift",
  "ellipticalMachine",
  "facePull",
  "flatKneeRaise",
  "flatLegRaise",
  "frontRaise",
  "frontSquat",
  "gobletSquat",
  "goodMorning",
  "hackSquat",
  "hammerCurl",
  "handstandPushUp",
  "hangClean",
  "hangSnatch",
  "hangingLegRaise",
  "highKneeSkips",
  "hipAbductor",
  "hipThrust",
  "inclineBenchPress",
  "inclineChestFly",
  "inclineChestPress",
  "inclineCurl",
  "inclineRow",
  "invertedRow",
  "isoLateralChestPress",
  "isoLateralRow",
  "jackknifeSitUp",
  "jumpRope",
  "jumpSquat",
  "jumpingJack",
  "kettlebellSwing",
  "kettlebellTurkishGetUp",
  "kippingPullUp",
  "kneeRaise",
  "kneelingPulldown",
  "kneestoElbows",
  "latPulldown",
  "lateralBoxJump",
  "lateralRaise",
  "legExtension",
  "legPress",
  "lunge",
  "lyingLegCurl",
  "mountainClimber",
  "muscleUp",
  "obliqueCrunch",
  "overheadPress",
  "overheadSquat",
  "pecDeck",
  "pendlayRow",
  "pistolSquat",
  "plank",
  "powerClean",
  "powerSnatch",
  "preacherCurl",
  "pressUnder",
  "pullUp",
  "pullover",
  "pushPress",
  "pushUp",
  "reverseCrunch",
  "reverseCurl",
  "reverseFly",
  "reverseGripConcentrationCurl",
  "reversePlank",
  "romanianDeadlift",
  "rowing",
  "russianTwist",
  "seatedCalfRaise",
  "seatedLegCurl",
  "seatedLegPress",
  "seatedOverheadPress",
  "seatedPalmsUpWristCurl",
  "seatedRow",
  "seatedWideGripRow",
  "shoulderPress",
  "shrug",
  "sideBend",
  "sidePlank",
  "singleLegBridge",
  "singleLegDeadlift",
  "sitUp",
  "skullcrusher",
  "snatch",
  "snatchPull",
  "splitJerk",
  "squat",
  "squatRow",
  "standingCalfRaise",
  "stepUp",
  "stiffLegDeadlift",
  "straightLegDeadlift",
  "sumoDeadlift",
  "sumoDeadliftHighPull",
  "superman",
  "tBarRow",
  "thruster",
  "toesToBar",
  "torsoRotation",
  "trapBarDeadlift",
  "tricepsDip",
  "tricepsExtension",
  "tricepsPushdown",
  "uprightRow",
  "vUp",
  "widePullUp",
  "wristRoller",
  "zercherSquat",
] as const;

export const exercises: Record<IExerciseId, IExercise> = {
  abWheel: {
    id: "abWheel",
    name: "Ab Wheel",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  arnoldPress: {
    id: "arnoldPress",
    name: "Arnold Press",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {
      shoulders: 100,
      triceps: 50,
    },
  },
  backExtension: {
    id: "backExtension",
    name: "Back Extension",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {
      back: 100,
    },
  },
  ballSlams: {
    id: "ballSlams",
    name: "Ball Slams",
    warmupSets: warmupEmpty,
    defaultBar: undefined,
    muscles: {
      back: 100,
      abs: 50,
    },
  },
  battleRopes: {
    id: "battleRopes",
    name: "Battle Ropes",
    warmupSets: warmupEmpty,
    defaultBar: undefined,
    muscles: {},
  },
  benchDip: {
    id: "benchDip",
    name: "Bench Dip",
    warmupSets: warmupEmpty,
    defaultBar: undefined,
    muscles: {
      triceps: 100,
      chest: 50,
    },
  },
  benchPress: {
    id: "benchPress",
    name: "Bench Press",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {
      chest: 100,
      shoulders: 80,
      triceps: 50,
    },
  },
  benchPressCloseGrip: {
    id: "benchPressCloseGrip",
    name: "Bench Press Close Grip",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {
      triceps: 100,
      chest: 50,
    },
  },
  benchPressWideGrip: {
    id: "benchPressWideGrip",
    name: "Bench Press Wide Grip",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  bentOverOneArmRow: {
    id: "bentOverOneArmRow",
    name: "Bent Over One Arm Row",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {
      back: 100,
    },
  },
  bentOverRow: {
    id: "bentOverRow",
    name: "Bent Over Row",
    warmupSets: warmup95,
    defaultBar: "barbell",
    muscles: {
      back: 100,
      biceps: 50,
    },
  },
  bicepCurl: {
    id: "bicepCurl",
    name: "Bicep Curl",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {
      biceps: 100,
    },
  },
  bicycleCrunch: {
    id: "bicycleCrunch",
    name: "Bicycle Crunch",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {
      abs: 100,
    },
  },
  boxJump: {
    id: "boxJump",
    name: "Box Jump",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {
      hamstrings: 100,
      quadriceps: 100,
    },
  },
  boxSquat: {
    id: "boxSquat",
    name: "Box Squat",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {
      hamstrings: 100,
      glutes: 100,
      quadriceps: 50,
    },
  },
  bulgarianSplitSquat: {
    id: "bulgarianSplitSquat",
    name: "Bulgarian Split Squat",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {
      quadriceps: 100,
      hamstrings: 50,
      glutes: 50,
    },
  },
  burpee: {
    id: "burpee",
    name: "Burpee",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  cableCrossover: {
    id: "cableCrossover",
    name: "Cable Crossover",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  cableCrunch: {
    id: "cableCrunch",
    name: "Cable Crunch",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  cableKickback: {
    id: "cableKickback",
    name: "Cable Kickback",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  cablePullThrough: {
    id: "cablePullThrough",
    name: "Cable Pull Through",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  cableTwist: {
    id: "cableTwist",
    name: "Cable Twist",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  calfPressOnLegPress: {
    id: "calfPressOnLegPress",
    name: "Calf Press on Leg Press",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  calfPressOnSeatedLegPress: {
    id: "calfPressOnSeatedLegPress",
    name: "Calf Press on Seated Leg Press",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  chestDip: {
    id: "chestDip",
    name: "Chest Dip",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  chestFly: {
    id: "chestFly",
    name: "Chest Fly",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  chestPress: {
    id: "chestPress",
    name: "Chest Press",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  chinUp: {
    id: "chinUp",
    name: "Chin Up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {
      back: 80,
      biceps: 50,
      chest: 30,
      shoulders: 20,
      abs: 15,
      forearms: 10,
    },
  },
  clean: {
    id: "clean",
    name: "Clean",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  cleanandJerk: {
    id: "cleanandJerk",
    name: "Clean and Jerk",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  concentrationCurl: {
    id: "concentrationCurl",
    name: "Concentration Curl",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  crossBodyCrunch: {
    id: "crossBodyCrunch",
    name: "Cross Body Crunch",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  crunch: {
    id: "crunch",
    name: "Crunch",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  cycling: {
    id: "cycling",
    name: "Cycling",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  deadlift: {
    id: "deadlift",
    name: "Deadlift",
    warmupSets: warmup95,
    defaultBar: "barbell",
    muscles: {
      abs: 20,
      hamstrings: 40,
      glutes: 60,
      quadriceps: 80,
      back: 70,
      biceps: 15,
      forearms: 30,
    },
  },
  deadliftHighPull: {
    id: "deadliftHighPull",
    name: "Deadlift High Pull",
    warmupSets: warmup95,
    defaultBar: "barbell",
    muscles: {},
  },
  declineBenchPress: {
    id: "declineBenchPress",
    name: "Decline Bench Press",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  declineCrunch: {
    id: "declineCrunch",
    name: "Decline Crunch",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  deficitDeadlift: {
    id: "deficitDeadlift",
    name: "Deficit Deadlift",
    warmupSets: warmup95,
    defaultBar: "barbell",
    muscles: {},
  },
  ellipticalMachine: {
    id: "ellipticalMachine",
    name: "Elliptical Machine",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  facePull: {
    id: "facePull",
    name: "Face Pull",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  flatKneeRaise: {
    id: "flatKneeRaise",
    name: "Flat Knee Raise",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  flatLegRaise: {
    id: "flatLegRaise",
    name: "Flat Leg Raise",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  frontRaise: {
    id: "frontRaise",
    name: "Front Raise",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  frontSquat: {
    id: "frontSquat",
    name: "Front Squat",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  gobletSquat: {
    id: "gobletSquat",
    name: "Goblet Squat",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  goodMorning: {
    id: "goodMorning",
    name: "Good Morning",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  hackSquat: {
    id: "hackSquat",
    name: "Hack Squat",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  hammerCurl: {
    id: "hammerCurl",
    name: "Hammer Curl",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  handstandPushUp: {
    id: "handstandPushUp",
    name: "Handstand Push Up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  hangClean: {
    id: "hangClean",
    name: "Hang Clean",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  hangSnatch: {
    id: "hangSnatch",
    name: "Hang Snatch",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  hangingLegRaise: {
    id: "hangingLegRaise",
    name: "Hanging Leg Raise",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  highKneeSkips: {
    id: "highKneeSkips",
    name: "High Knee Skips",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  hipAbductor: {
    id: "hipAbductor",
    name: "Hip Abductor",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  hipThrust: {
    id: "hipThrust",
    name: "Hip Thrust",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  inclineBenchPress: {
    id: "inclineBenchPress",
    name: "Incline Bench Press",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  inclineChestFly: {
    id: "inclineChestFly",
    name: "Incline Chest Fly",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  inclineChestPress: {
    id: "inclineChestPress",
    name: "Incline Chest Press",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  inclineCurl: {
    id: "inclineCurl",
    name: "Incline Curl",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  inclineRow: {
    id: "inclineRow",
    name: "Incline Row",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  invertedRow: {
    id: "invertedRow",
    name: "Inverted Row",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  isoLateralChestPress: {
    id: "isoLateralChestPress",
    name: "Iso-Lateral Chest Press",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  isoLateralRow: {
    id: "isoLateralRow",
    name: "Iso-Lateral Row",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  jackknifeSitUp: {
    id: "jackknifeSitUp",
    name: "Jackknife Sit Up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  jumpRope: {
    id: "jumpRope",
    name: "Jump Rope",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  jumpSquat: {
    id: "jumpSquat",
    name: "Jump Squat",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  jumpingJack: {
    id: "jumpingJack",
    name: "Jumping Jack",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  kettlebellSwing: {
    id: "kettlebellSwing",
    name: "Kettlebell Swing",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  kettlebellTurkishGetUp: {
    id: "kettlebellTurkishGetUp",
    name: "Kettlebell Turkish Get Up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  kippingPullUp: {
    id: "kippingPullUp",
    name: "Kipping Pull Up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  kneeRaise: {
    id: "kneeRaise",
    name: "Knee Raise",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  kneelingPulldown: {
    id: "kneelingPulldown",
    name: "Kneeling Pulldown",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  kneestoElbows: {
    id: "kneestoElbows",
    name: "Knees to Elbows",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  latPulldown: {
    id: "latPulldown",
    name: "Lat Pulldown",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  lateralBoxJump: {
    id: "lateralBoxJump",
    name: "Lateral Box Jump",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  lateralRaise: {
    id: "lateralRaise",
    name: "Lateral Raise",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  legExtension: {
    id: "legExtension",
    name: "Leg Extension",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  legPress: {
    id: "legPress",
    name: "Leg Press",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  lunge: {
    id: "lunge",
    name: "Lunge",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  lyingLegCurl: {
    id: "lyingLegCurl",
    name: "Lying Leg Curl",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  mountainClimber: {
    id: "mountainClimber",
    name: "Mountain Climber",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  muscleUp: {
    id: "muscleUp",
    name: "Muscle Up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  obliqueCrunch: {
    id: "obliqueCrunch",
    name: "Oblique Crunch",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  overheadPress: {
    id: "overheadPress",
    name: "Overhead Press",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {
      shoulders: 100,
      chest: 50,
      biceps: 30,
      triceps: 15,
    },
  },
  overheadSquat: {
    id: "overheadSquat",
    name: "Overhead Squat",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  pecDeck: {
    id: "pecDeck",
    name: "Pec Deck",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  pendlayRow: {
    id: "pendlayRow",
    name: "Pendlay Row",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  pistolSquat: {
    id: "pistolSquat",
    name: "Pistol Squat",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  plank: {
    id: "plank",
    name: "Plank",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  powerClean: {
    id: "powerClean",
    name: "Power Clean",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  powerSnatch: {
    id: "powerSnatch",
    name: "Power Snatch",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  preacherCurl: {
    id: "preacherCurl",
    name: "Preacher Curl",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  pressUnder: {
    id: "pressUnder",
    name: "Press Under",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  pullUp: {
    id: "pullUp",
    name: "Pull Up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {
      back: 100,
      biceps: 30,
      chest: 30,
      shoulders: 20,
      abs: 15,
      forearms: 10,
    },
  },
  pullover: {
    id: "pullover",
    name: "Pullover",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  pushPress: {
    id: "pushPress",
    name: "Push Press",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  pushUp: {
    id: "pushUp",
    name: "Push Up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  reverseCrunch: {
    id: "reverseCrunch",
    name: "Reverse Crunch",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  reverseCurl: {
    id: "reverseCurl",
    name: "Reverse Curl",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  reverseFly: {
    id: "reverseFly",
    name: "Reverse Fly",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  reverseGripConcentrationCurl: {
    id: "reverseGripConcentrationCurl",
    name: "Reverse Grip Concentration Curl",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  reversePlank: {
    id: "reversePlank",
    name: "Reverse Plank",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  romanianDeadlift: {
    id: "romanianDeadlift",
    name: "Romanian Deadlift",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  rowing: {
    id: "rowing",
    name: "Rowing",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  russianTwist: {
    id: "russianTwist",
    name: "Russian Twist",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  seatedCalfRaise: {
    id: "seatedCalfRaise",
    name: "Seated Calf Raise",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  seatedLegCurl: {
    id: "seatedLegCurl",
    name: "Seated Leg Curl",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  seatedLegPress: {
    id: "seatedLegPress",
    name: "Seated Leg Press",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  seatedOverheadPress: {
    id: "seatedOverheadPress",
    name: "Seated Overhead Press",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  seatedPalmsUpWristCurl: {
    id: "seatedPalmsUpWristCurl",
    name: "Seated Palms Up Wrist Curl",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  seatedRow: {
    id: "seatedRow",
    name: "Seated Row",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  seatedWideGripRow: {
    id: "seatedWideGripRow",
    name: "Seated Wide Grip Row",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  shoulderPress: {
    id: "shoulderPress",
    name: "Shoulder Press",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  shrug: {
    id: "shrug",
    name: "Shrug",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  sideBend: {
    id: "sideBend",
    name: "Side Bend",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  sidePlank: {
    id: "sidePlank",
    name: "Side Plank",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  singleLegBridge: {
    id: "singleLegBridge",
    name: "Single Leg Bridge",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  singleLegDeadlift: {
    id: "singleLegDeadlift",
    name: "Single Leg Deadlift",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  sitUp: {
    id: "sitUp",
    name: "Sit Up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  skullcrusher: {
    id: "skullcrusher",
    name: "Skullcrusher",
    warmupSets: warmup10,
    defaultBar: "ezbar",
    muscles: {},
  },
  snatch: {
    id: "snatch",
    name: "Snatch",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  snatchPull: {
    id: "snatchPull",
    name: "Snatch Pull",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  splitJerk: {
    id: "splitJerk",
    name: "Split Jerk",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  squat: {
    id: "squat",
    name: "Squat",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {
      quadriceps: 70,
      hamstrings: 30,
      glutes: 30,
      back: 50,
      abs: 10,
    },
  },
  squatRow: {
    id: "squatRow",
    name: "Squat Row",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  standingCalfRaise: {
    id: "standingCalfRaise",
    name: "Standing Calf Raise",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  stepUp: {
    id: "stepUp",
    name: "Step up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  stiffLegDeadlift: {
    id: "stiffLegDeadlift",
    name: "Stiff Leg Deadlift",
    warmupSets: warmup95,
    defaultBar: "barbell",
    muscles: {},
  },
  straightLegDeadlift: {
    id: "straightLegDeadlift",
    name: "Straight Leg Deadlift",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  sumoDeadlift: {
    id: "sumoDeadlift",
    name: "Sumo Deadlift",
    warmupSets: warmup95,
    defaultBar: "barbell",
    muscles: {},
  },
  sumoDeadliftHighPull: {
    id: "sumoDeadliftHighPull",
    name: "Sumo Deadlift High Pull",
    warmupSets: warmup95,
    defaultBar: "barbell",
    muscles: {},
  },
  superman: {
    id: "superman",
    name: "Superman",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  tBarRow: {
    id: "tBarRow",
    name: "T Bar Row",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  thruster: {
    id: "thruster",
    name: "Thruster",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
  toesToBar: {
    id: "toesToBar",
    name: "Toes To Bar",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  torsoRotation: {
    id: "torsoRotation",
    name: "Torso Rotation",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  trapBarDeadlift: {
    id: "trapBarDeadlift",
    name: "Trap Bar Deadlift",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  tricepsDip: {
    id: "tricepsDip",
    name: "Triceps Dip",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  tricepsExtension: {
    id: "tricepsExtension",
    name: "Triceps Extension",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  tricepsPushdown: {
    id: "tricepsPushdown",
    name: "Triceps Pushdown",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  uprightRow: {
    id: "uprightRow",
    name: "Upright Row",
    warmupSets: warmup10,
    defaultBar: "dumbbell",
    muscles: {},
  },
  vUp: {
    id: "vUp",
    name: "V Up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  widePullUp: {
    id: "widePullUp",
    name: "Wide Pull Up",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  wristRoller: {
    id: "wristRoller",
    name: "Wrist Roller",
    warmupSets: warmup10,
    defaultBar: undefined,
    muscles: {},
  },
  zercherSquat: {
    id: "zercherSquat",
    name: "Zercher Squat",
    warmupSets: warmup45,
    defaultBar: "barbell",
    muscles: {},
  },
};

export const TExerciseId = t.keyof(
  exerciseTypes.reduce<Record<IArrayElement<typeof exerciseTypes>, null>>((memo, exerciseType) => {
    memo[exerciseType] = null;
    return memo;
  }, {} as Record<IArrayElement<typeof exerciseTypes>, null>),
  "TExerciseId"
);
export type IExerciseId = t.TypeOf<typeof TExerciseId>;

export const TExerciseType = t.intersection(
  [
    t.interface({
      id: TExerciseId,
    }),
    t.partial({
      bar: TBarKey,
    }),
  ],
  "TExerciseType"
);
export type IExerciseType = t.TypeOf<typeof TExerciseType>;

export type IMuscle =
  | "lowerBack"
  | "shoulders"
  | "triceps"
  | "back"
  | "abs"
  | "glutes"
  | "hamstrings"
  | "quadriceps"
  | "chest"
  | "biceps"
  | "calves"
  | "abductors"
  | "adductors"
  | "neck"
  | "trapezius"
  | "forearms"
  | "upperLegs";

export type IExercise = {
  id: IExerciseId;
  name: string;
  warmupSets: (weight: IWeight, settings: ISettings, bar?: IBarKey) => ISet[];
  bar?: keyof IBars;
  defaultBar?: keyof IBars;
  muscles: Partial<Record<IMuscle, number>>;
};

function warmup45(weight: IWeight, settings: ISettings, bar?: IBarKey): ISet[] {
  return warmup({ 45: 0.8, 90: 0.5, 120: 0.3 })(weight, settings, bar);
}

function warmup95(weight: IWeight, settings: ISettings, bar?: IBarKey): ISet[] {
  return warmup({ 95: 0.8, 125: 0.5, 150: 0.3 })(weight, settings, bar);
}

function warmup10(weight: IWeight, settings: ISettings, bar?: IBarKey): ISet[] {
  return warmup({ 10: 0.8, 30: 0.5, 60: 0.3 })(weight, settings, bar);
}

function warmup(mapping: Record<number, number>): (weight: IWeight, settings: ISettings, bar?: IBarKey) => ISet[] {
  return (weight: IWeight, settings: ISettings, bar?: IBarKey): ISet[] => {
    const percents: number[] = [];
    ObjectUtils.keys(mapping).forEach((weightValue) => {
      const percent = mapping[weightValue];
      if (Weight.gt(weight, Weight.build(weightValue, "lb"))) {
        percents.unshift(percent);
      }
    });
    return percents.map((percent) => {
      return {
        reps: 5,
        weight: Weight.max(
          bar != null ? Settings.bars(settings)[bar] : Weight.build(0, settings.units),
          Weight.roundConvertTo(Weight.multiply(weight, percent), settings, bar)
        ),
      };
    });
  };
}

function warmupEmpty(weight: IWeight): ISet[] {
  return [];
}

export namespace Exercise {
  export function get(type: IExerciseType): IExercise {
    return { ...exercises[type.id], bar: type.bar };
  }

  export function eq(a: IExerciseType, b: IExerciseType): boolean {
    return a.id === b.id && a.bar === b.bar;
  }

  export function getWarmupSets(exercise: IExerciseType, weight: IWeight, settings: ISettings): ISet[] {
    return get(exercise).warmupSets(weight, settings, exercise.bar);
  }
}
