/* eslint-disable @typescript-eslint/no-explicit-any */
// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
const spec_Keyword: any = { __proto__: null, if: 90, else: 92 };
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "*bQcQPOOO!`QPO'#CxOOQO'#Cd'#CdO#PQPO'#CdO$`QPO'#DSOcQPO'#ChO$gQPO'#CiO$nQPO'#CkO$sQPO'#CoO&WQPO'#DSOcQPO'#CvOOQO'#DS'#DSQcQPOOOcQPO,58yOcQPO,58yOcQPO,58yOcQPO,58yOcQPO,59UOOQO,59O,59OOOQO,59Q,59QO&bQPO,59SOOQO,59T,59TO&iQPO,59TO&pQPO,59VO&uQQO,59ZO'PQPO,59aOcQPO,59XOcQPO,59_OOQO,59b,59bOOQO-E6v-E6vO(bQPO1G.eOOQO1G.e1G.eO(iQPO1G.eO(pQPO1G.eO)zQPO1G.pOOQO1G.n1G.nOOQO1G.o1G.oO*RQPO1G.qO+`QPO'#CpOOQO'#Cq'#CqOOQO'#Cr'#CrOOQO'#Cp'#CpO+jQPO1G.uO+rQPO1G.{OcQPO'#C{O+|QPO1G.{OOQO1G.{1G.{O,UQPO1G.sO-RQPO1G.yOcQPO7+$[O.OQPO7+$]O.WQPO7+$]O&uQQO'#CzO/eQPO7+$aOOQO7+$a7+$aO/mQPO7+$gOOQO7+$g7+$gO/uQPO,59gOOQO-E6y-E6yO0PQPO<<GvO$nQPO,59eOOQO<<Gw<<GwO.OQPO<<GwOOQO-E6w-E6wOOQO,59f,59fOOQO-E6x-E6xOOQO<<G{<<G{OOQO<<HR<<HRO&pQPO1G/POOQOAN=cAN=cP.RQPO'#CyOOQO7+$k7+$k",
  stateData:
    "1V~OrOSPOSsOStOSuOS~OSROXQO`WObXOkYOwTOyUO}VO~OS]OT^OU_OV`O{aO~OXlX`lXblXklXplXwlXylX}lXzlX~P}OXbO~OSvXTvXUvXVvXXvX`vXbvXkvXpvXwvXyvX{vX}vXxvXzvX|vX!SvX!UvX~OZcO~P#UOzeO~PcOwTO~OwiO!PhOScXTcXUcXVcXXcX`cXbcXhcXkcXpcXycX{cX}cX!TcXxcXzcX|cX!ScX!UcX~OhkO!TjO~P#UOxsO~P}OztO~PcOyUO~O!QwO!RxO~PcOx!OO!U|O~PcOT^OURiVRiXRi`RibRikRipRiwRiyRi{Ri}RixRizRi|Ri!SRi!URi~OSRi~P'ZOS]O~P'ZOS]OT^OU_OVRiXRi`RibRikRipRiwRiyRi{Ri}RixRizRi|Ri!SRi!URi~O|!RO~P}O!O!SOS_iT_iU_iV_iX_i`_ib_ik_ip_iw_iy_i{_i}_ix_iz_i|_i!S_i!U_i~O|dX!SdX~P}O|!UO!S!WO~Ox!YO!U|O~P}Ox!YO!U|O~OXai`aibaikaipaiwaiyai}aixaizai|ai!Sai!Uai~P}OXgi`gibgikgipgiwgiygi}gixgizgi|gi!Sgi!Ugi~P}OyUO}!^O~O!O!`OS_qT_qU_qV_qX_q`_qb_qk_qp_qw_qy_q{_q}_qx_qz_q|_q!S_q!U_q~O|!UO!S!dO~Ox!eO!U|O~Oxoa!Uoa~P}OX^y`^yb^yk^yp^yw^yy^y}^yx^yz^y|^y!S^y!U^y~P}OPTXSbZb`~",
  goto:
    "&`wPPPxPPPP!^PxP!r#^xxPxP$O$d$j$jxPxxP$n$x%O%UPPPPPP%`uZOTUY[]^_`afhijk|!R!UuSOTUY[]^_`afhijk|!R!UtZOTUY[]^_`afhijk|!R!UQgVR!f!^tZOTUY[]^_`afhijk|!R!UQugQ!_!SQ!g!`R!i!fuXOTUY[]^_`afhijk|!R!UQzhR!b!UTyh!UQ[OQfUTm[fQ!TuR!a!TQ!VzR!c!VQ}iQ!X{T![}!XWPOU[fQdTQlYQn]Qo^Qp_Qq`QraSvh!UQ{iQ!PjQ!QkQ!Z|R!]!R",
  nodeNames:
    "⚠ LineComment Program BinaryExpression Plus Times Cmp AndOr NumberExpression Number WeightExpression Unit ParenthesisExpression BlockExpression Ternary IfExpression Keyword AssignmentExpression StateVariable VariableExpression VariableIndex Wildcard Current IncAssignmentExpression IncAssignment FunctionExpression UnaryExpression Not",
  maxTerm: 52,
  skippedNodes: [0, 1],
  repeatNodeCount: 4,
  tokenData:
    "._~RzX^#upq#uqr$juv$wvw$|xy%Xyz%^z{%c{|%r|}%z}!O%r!O!P&P!P!Q&_!Q!['R![!]'w!]!^'|!^!_(R!_!`(Z!`!a(R!a!b(c!c!}(h!}#O(y#P#Q)O#R#S)T#T#_(h#_#`)Y#`#a*U#a#g(h#g#h*m#h#o(h#o#p-j#p#q-w#q#r-}#r#s.S#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~#zYr~X^#upq#u#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~$oPk~!_!`$r~$wOU~P$|OTP~%PPvw%S~%XOV~~%^Ow~~%cOx~R%jP!QQTP!_!`%mP%rOhP~%wPS~!_!`%m~&PO!U~~&SP!Q![&V~&[PX~!Q![&V~&dQTP!P!Q&j!_!`%m~&oSP~OY&jZ;'S&j;'S;=`&{<%lO&j~'OP;=`<%l&j~'WQX~!O!P'^!Q!['R~'cPX~!Q!['f~'kQX~!O!P'q!Q!['f~'tP!Q!['f~'|O|~~(ROs~~(WPU~!_!`$r~(`P!T~!_!`$r~(hO{~~(mS`~!Q![(h!c!}(h#R#S(h#T#o(h~)OO!P~~)TO!S~~)YO!R~~)_U`~!Q![(h!c!}(h#R#S(h#T#Z(h#Z#[)q#[#o(h~)xSZ~`~!Q![(h!c!}(h#R#S(h#T#o(h~*ZU`~!Q![(h!c!}(h#R#S(h#T#U(h#U#V)q#V#o(h~*rU`~!Q![(h!c!}(h#R#S(h#T#h(h#h#i+U#i#o(h~+ZT`~!Q![(h!c!}(h#R#S(h#T#U+j#U#o(h~+oU`~!Q![(h!c!}(h#R#S(h#T#h(h#h#i,R#i#o(h~,WU`~!Q![(h!c!}(h#R#S(h#T#X(h#X#Y,j#Y#o(h~,oT`~!O!P-O!Q![(h!c!}(h#R#S(h#T#o(h~-RQ!c!}-X#T#o-X~-^Sb~!Q![-X!c!}-X#R#S-X#T#o-X~-oPy~#r#s-r~-wOt~~-zP#p#q%S~.SOz~~.VP#q#r.Y~._Ou~",
  tokenizers: [0, 1],
  topRules: { Program: [0, 2] },
  specialized: [{ term: 16, get: (value: any) => spec_Keyword[value] || -1 }],
  tokenPrec: 734,
});
