/* eslint-disable @typescript-eslint/no-explicit-any */
// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
const spec_Keyword: any = { __proto__: null, if: 92, else: 94 };
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "*bQcQPOOO!cQPO'#CyOOQO'#Cd'#CdO#VQPO'#CdO$iQPO'#DTOcQPO'#CiO$pQPO'#CjO$wQPO'#ClO$|QPO'#CpO&dQPO'#DTOcQPO'#CwOOQO'#DT'#DTQcQPOOOcQPO,58yOcQPO,58yOcQPO,58yOcQPO,58yOcQPO,59VOOQO,59O,59OOOQO,59Q,59QO&nQPO,59TOOQO,59U,59UO&uQPO,59UO&|QPO,59WO'RQQO,59[O']QPO,59bOcQPO,59YOcQPO,59`OOQO,59c,59cOOQO-E6w-E6wO(qQPO1G.eOOQO1G.e1G.eO(xQPO1G.eO)PQPO1G.eO*^QPO1G.qOOQO1G.o1G.oOOQO1G.p1G.pO*eQPO1G.rO+uQPO'#CqOOQO'#Cr'#CrOOQO'#Cs'#CsOOQO'#Cq'#CqO,PQPO1G.vO,XQPO1G.|OcQPO'#C|O,cQPO1G.|OOQO1G.|1G.|O,kQPO1G.tO-kQPO1G.zOcQPO7+$]O.kQPO7+$^O.sQPO7+$^O'RQQO'#C{O0TQPO7+$bOOQO7+$b7+$bO0]QPO7+$hOOQO7+$h7+$hO0eQPO,59hOOQO-E6z-E6zO0oQPO<<GwO$wQPO,59fOOQO<<Gx<<GxO.kQPO<<GxOOQO-E6x-E6xOOQO,59g,59gOOQO-E6y-E6yOOQO<<G|<<G|OOQO<<HS<<HSO&|QPO1G/QOOQOAN=dAN=dP.nQPO'#CzOOQO7+$l7+$l",
  stateData:
    "1y~OsOSPOStOSuOSvOS~OSROXQO[ZOaWOcXOlYOxTOzUO!OVO~OS]OT^OU_OV`O|aO~OXmX[mXamXcmXlmXqmXxmXzmX!OmX{mX~P!QOXbO~OSwXTwXUwXVwXXwX[wXawXcwXlwXqwXxwXzwX|wX!OwXywX{wX}wX!TwX!VwX~OZcO~P#[O{eO~PcOxTO~OxiO!QhOSdXTdXUdXVdXXdX[dXadXcdXidXldXqdXzdX|dX!OdX!UdXydX{dX}dX!TdX!VdX~OikO!UjO~P#[OysO~P!QO{tO~PcOzUO~O!RwO!SxO~PcOy!OO!V|O~PcOT^OURiVRiXRi[RiaRicRilRiqRixRizRi|Ri!ORiyRi{Ri}Ri!TRi!VRi~OSRi~P'gOS]O~P'gOS]OT^OU_OVRiXRi[RiaRicRilRiqRixRizRi|Ri!ORiyRi{Ri}Ri!TRi!VRi~O}!RO~P!QO!P!SOS`iT`iU`iV`iX`i[`ia`ic`il`iq`ix`iz`i|`i!O`iy`i{`i}`i!T`i!V`i~O}eX!TeX~P!QO}!UO!T!WO~Oy!YO!V|O~P!QOy!YO!V|O~OXbi[biabicbilbiqbixbizbi!Obiybi{bi}bi!Tbi!Vbi~P!QOXhi[hiahichilhiqhixhizhi!Ohiyhi{hi}hi!Thi!Vhi~P!QOzUO!O!^O~O!P!`OS`qT`qU`qV`qX`q[`qa`qc`ql`qq`qx`qz`q|`q!O`qy`q{`q}`q!T`q!V`q~O}!UO!T!dO~Oy!eO!V|O~Oypa!Vpa~P!QOX_y[_ya_yc_yl_yq_yx_yz_y!O_yy_y{_y}_y!T_y!V_y~P!QOPTc[XSZaZ~",
  goto:
    "&axPPPyPPPP!_PyPP!s#_yyPyP$P$e$k$kyPyyP$o$y%P%VPPPPPP%auZOTUY[]^_`afhijk|!R!UuSOTUY[]^_`afhijk|!R!UtZOTUY[]^_`afhijk|!R!UQgVR!f!^tZOTUY[]^_`afhijk|!R!UQugQ!_!SQ!g!`R!i!fuXOTUY[]^_`afhijk|!R!UQzhR!b!UTyh!UQ[OQfUTm[fQ!TuR!a!TQ!VzR!c!VQ}iQ!X{T![}!XWPOU[fQdTQlYQn]Qo^Qp_Qq`QraSvh!UQ{iQ!PjQ!QkQ!Z|R!]!R",
  nodeNames:
    "⚠ LineComment Program BinaryExpression Plus Times Cmp AndOr NumberExpression Number WeightExpression Unit Percentage ParenthesisExpression BlockExpression Ternary IfExpression Keyword AssignmentExpression StateVariable VariableExpression VariableIndex Wildcard Current IncAssignmentExpression IncAssignment FunctionExpression UnaryExpression Not",
  maxTerm: 53,
  skippedNodes: [0, 1],
  repeatNodeCount: 4,
  tokenData:
    ".p~RzX^#upq#uqr$juv$wvw$|xy%Xyz%^z{%c{|%r|}%z}!O%r!O!P&P!P!Q&g!Q!['Z![!](Y!]!^(_!^!_(d!_!`(l!`!a(d!a!b(t!c!}(y!}#O)[#P#Q)a#R#S)f#T#_(y#_#`)k#`#a*g#a#g(y#g#h+O#h#o(y#o#p-{#p#q.Y#q#r.`#r#s.e#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~#zYs~X^#upq#u#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~$oPl~!_!`$r~$wOU~P$|OTP~%PPvw%S~%XOV~~%^Ox~~%cOy~R%jP!RQTP!_!`%mP%rOiP~%wPS~!_!`%m~&PO!V~~&SP!Q![&V~&[QX~uv&b!Q![&V~&gO[~~&lQTP!P!Q&r!_!`%m~&wSP~OY&rZ;'S&r;'S;=`'T<%lO&r~'WP;=`<%l&r~'`RX~uv&b!O!P'i!Q!['Z~'nQX~uv&b!Q!['t~'yRX~uv&b!O!P(S!Q!['t~(VP!Q!['t~(_O}~~(dOt~~(iPU~!_!`$r~(qP!U~!_!`$r~(yO|~~)OSa~!Q![(y!c!}(y#R#S(y#T#o(y~)aO!Q~~)fO!T~~)kO!S~~)pUa~!Q![(y!c!}(y#R#S(y#T#Z(y#Z#[*S#[#o(y~*ZSZ~a~!Q![(y!c!}(y#R#S(y#T#o(y~*lUa~!Q![(y!c!}(y#R#S(y#T#U(y#U#V*S#V#o(y~+TUa~!Q![(y!c!}(y#R#S(y#T#h(y#h#i+g#i#o(y~+lTa~!Q![(y!c!}(y#R#S(y#T#U+{#U#o(y~,QUa~!Q![(y!c!}(y#R#S(y#T#h(y#h#i,d#i#o(y~,iUa~!Q![(y!c!}(y#R#S(y#T#X(y#X#Y,{#Y#o(y~-QTa~!O!P-a!Q![(y!c!}(y#R#S(y#T#o(y~-dQ!c!}-j#T#o-j~-oSc~!Q![-j!c!}-j#R#S-j#T#o-j~.QPz~#r#s.T~.YOu~~.]P#p#q%S~.eO{~~.hP#q#r.k~.pOv~",
  tokenizers: [0, 1],
  topRules: { Program: [0, 2] },
  specialized: [{ term: 17, get: (value: any) => spec_Keyword[value] || -1 }],
  tokenPrec: 767,
});
